---
- name: "Distro Check"
  hosts: all
  tags: check
  tasks:
    - debug: "{{ ansible_facts['distribution'] }}"

- name: "Dev Env Setup with sudo"
  hosts: all
  tags: root
  connection: local
  become: yes
  become_method: sudo
  
  roles:
    - common  
    - go

- name: "go tools via go get (Non Root)"
  tags: go
  hosts: localhost
  connection: local

  roles:
    - go_tools

- name: "Rust based tools via cargo (Non Root)"
  tags: cargo
  hosts: localhost
  connection: local

  roles:    
    - cargo_tools 
    
- name: "dotfiles and config (Non Root)"
  tags: dotfiles
  hosts: localhost
  connection: local

  roles:    
    - dotfiles
     

- name: "Other (Non Root)"
  tags: other
  hosts: localhost
  connection: local

  roles:  
    - other 