---
- name: "Distro Check"
  hosts: all
  tags: check
  tasks:
    - debug: "{{ ansible_facts['distribution'] }}"

- name: "Dev Env Setup with sudo"
  hosts: all
  tags: common
  connection: local
  become: yes
  become_method: sudo
  
  roles:
    - common  
    - go

- name: "py-tools"
  hosts: all
  tags: py
  become: yes
  become_method: sudo
  roles:  
    - py 

- name: "go tools via go get (Non Root)"
  tags: go
  hosts: all

  roles:
    - go_tools

- name: "Rust based tools via cargo (Non Root)"
  tags: cargo
  hosts: all

  roles:    
    - cargo_tools 
    
- name: "dotfiles and config (Non Root)"
  tags: dotfiles
  hosts: all

  roles:    
    - dotfiles
     
- name: "Other (Non Root)"
  tags: other
  hosts: all

  roles:  
    - other 

- name: "Docker"
  tags: docker
  hosts: all
  become: yes
  become_method: sudo

  roles:  
    - docker