---
- name: "Distro Check"
  hosts: all
  tags: test
  tasks:
    - debug: 
        msg: "{{ ansible_distribution }}"
    - command: lsb_release -cs
      register: dist_version
    - debug: 
        msg: "{{ dist_version.stdout}}"

- name: "Dev Env Setup with sudo"
  hosts: all
  tags: common
  connection: local
  become: yes
  become_method: sudo
  
  roles:
    - common  
    - go

- name: "py-tools"
  hosts: all
  tags: py
  become: yes
  become_method: sudo
  roles:  
    - py 

- name: "go tools via go get (Non Root)"
  tags: go
  hosts: all

  roles:
    - go_tools

- name: "Rust based tools via cargo (Non Root)"
  tags: cargo
  hosts: all

  roles:    
    - cargo_tools 
    
- name: "dotfiles and config (Non Root)"
  tags: dotfiles
  hosts: all

  roles:    
    - dotfiles
     
- name: "Other (Non Root)"
  tags: other
  hosts: all

  roles:  
    - other 

- name: "Docker"
  tags: docker
  hosts: all
  become: yes
  become_method: sudo

  roles:  
    - docker

- name: "minikube"
  tags: minikube
  hosts: all
  become: yes
  become_method: sudo
  
  roles:  
    - minikube

- name: "terraform"
  tags: terraform
  hosts: all
  become: yes
  become_method: sudo
  
  roles:  
    - terraform

- name: "gui"
  tags: gui
  hosts: all
  become: yes
  become_method: sudo

  roles:  
    - gui

- name: "dconf preferences"
  tags: gui-dconf
  hosts: all
  
  roles:
    - gui-dconf