# -----------------------------------------------------------
# Make sure to run init.sh inside wsl2_debian folder prior to this 

# Test Run: ansible-playbook wsl2.yml --check
# Specific Tags: ansible-playbook wsl2.yml --tags precheck 

# All: ansible-playbook wsl2.yml 
# -----------------------------------------------------------

---
# only targetting debian arm64 for now
 
- name: "Distro Check"
  hosts: all
  tags: precheck
  gather_facts: yes # needed for distro vars such as below   

  pre_tasks:
    - debug: 
        msg: "{{ ansible_distribution }}"
    - command: lsb_release -cs
      register: distro_version
    - debug: 
        msg: var=distro_version.stdout        

# Update and Upgrade
- name: "update and upgrade"
  hosts: all
  tags: update_upgrade
  become: true
  
  roles:
    - update_upgrade

# common tools
- name: common
  hosts: all
  tags: common
  become: true

  roles:
    - common
    - py
    
  tasks:    
    - include_role:
        name: go
      vars:
        target_version: "go1.15.6"
    - include_role:
        name: nvim
      vars:
          target_version: "v0.4.4"

# dotfiles
- name: "dotfiles and config (Non Root)"
  tags: dotfiles
  hosts: all

  roles:    
    - dotfiles

# Rust based tools via Cargo
- name: "Rust based tools via cargo (Non Root)"
  tags: cargo
  hosts: all

  roles:    
    - cargo_tools 

- name: "go tools via go get (Non Root)"
  tags: go
  hosts: all

  roles:
    - go_tools

- name: cloud native tools
  tags: cntools
  hosts: all
  become: true
  
  roles:  
    - cntools

- name: terraform
  tags: terraform
  hosts: all
  become: true

  tasks:
  - include_role:
      name: terraform        
    vars:
      distro_short: "deb"
      arch: "amd64"

  # Other 
- name: "Other (Non Root)"
  tags: other
  hosts: all

  roles:  
    - other 