# -----------------------------------------------------------
# Make sure to run init.sh inside wsl2_debian folder prior to this 

# Test Run: ansible-playbook wsl2.yml --check
# Specific Tags: ansible-playbook wsl2.yml --tags precheck 

# All: ansible-playbook wsl2.yml 
# -----------------------------------------------------------

---
- name: "Distro Check"
  hosts: all
  tags: precheck
  gather_facts: yes # needed for distro vars such as below  
  
  vars:
    distro: "{{ ansible_distribution }}"
    
  pre_tasks:
    - debug: 
        msg: "{{ distro }}"
    - command: lsb_release -cs
      register: distro_version
    - debug: 
        msg: var=distro_version.stdout        

- name: "essentials via apt"
  hosts: all
  tags: essentials
  become: true
  
  roles:
    - update_upgrade
