---
# wget "https://dl.google.com/go/$(curl https://golang.org/VERSION?m=text).linux-amd64.tar.gz"

- name: Get latest go version
  uri: 
    url: https://golang.org/VERSION?m=text     
    return_content: yes
  register: goversion

- debug: var=goversion.content

- name: Download and unarchive Go
  unarchive:
    src: "https://dl.google.com/go/{{ goversion.content }}.linux-amd64.tar.gz"      
    dest: /usr/local
    remote_src: yes
    

