- name: add apt key for terraform
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg 
    state: present

- name: get distro version
  command: lsb_release -cs
  register: distro_version
    
- name: add hashicorp repo
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ distro_version.stdout }} main"

- name: apt update
  apt:
    update_cache: yes
    name: terraform

